server:
  port: 8080
spring:
  application:
    name: "floristeria-api"
  profiles:
    active: dev
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    properties:
      hibernate:
        jdbc:
          time_zone: "America/Bogota"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
  #TODO: Pendiente por organizar completo